from typing import Optional
from pydantic import BaseModel, Field

class ReporteAnalisisSuelo(BaseModel):
    # Datos del solicitante
    clave_de_la_muestra: str = Field(..., description="Clave de identificación de la muestra")
    folio: str = Field(..., description="Folio del reporte")
    nombre: str = Field(..., description="Nombre del solicitante")
    direccion: str = Field(..., description="Dirección del solicitante")
    telefono: str = Field(..., description="Teléfono del solicitante")
    municipio: str = Field(..., description="Municipio del solicitante")
    estado: str = Field(..., description="Estado del solicitante")
    colonia: str = Field(..., description="Colonia del solicitante")
    correo: str = Field(..., description="Correo electrónico del solicitante")
    
    # Datos de la muestra
    estado_de_procedencia: str = Field(..., description="Estado de donde proviene la muestra")
    cultivo_anterior: str = Field(..., description="Cultivo anterior en el terreno")
    cultivo_a_establecer: str = Field(..., description="Cultivo que se planea establecer")
    fecha_de_muestreo: str = Field(..., description="Fecha en que se tomó la muestra")
    profundidad_de_muestreo: str = Field(..., description="Profundidad de muestreo")
    incorporo_residuos_de_cosecha: str = Field(..., description="Si se incorporaron residuos de cosecha")
    nombre_del_productor: str = Field(..., description="Nombre del productor")
    coordenadas_latitud: str = Field(..., description="Coordenadas de latitud")
    coordenadas_longitud: str = Field(..., description="Coordenadas de longitud")
    cantidad: str = Field(..., description="Cantidad de muestra")
    aceptable: str = Field(..., description="Si la muestra es aceptable")
    municipio_muestra: str = Field(..., description="Municipio donde se tomó la muestra")
    localidad: str = Field(..., description="Localidad de la muestra")
    tabla_lote: str = Field(..., description="Identificación del lote")
    meta_de_rendimiento: str = Field(..., description="Meta de rendimiento esperado")
    
    # Parámetros físicos
    arcilla: Optional[str] = Field(None, description="Porcentaje de arcilla")
    limo: Optional[str] = Field(None, description="Porcentaje de limo")
    arena: Optional[str] = Field(None, description="Porcentaje de arena")
    textura: Optional[str] = Field(None, description="Tipo de textura del suelo")
    porcentaje_saturacion: Optional[str] = Field(None, description="Porcentaje de saturación")
    densidad_aparente_DAP: Optional[str] = Field(None, description="Densidad aparente(DAP) en t m⁻³")
    
    # Parámetros químicos
    ph_agua_suelo: Optional[str] = Field(None, description="pH en relación 2:1 agua suelo")
    ph_agua_suelo_interpretacion: Optional[str] = Field(None, description="Interpretación del pH agua-suelo")
    ph_cacl2: Optional[str] = Field(None, description="pH en CaCl₂ 0.01 M")
    ph_cacl2_interpretacion: Optional[str] = Field(None, description="Interpretación del pH CaCl₂")
    ph_kcl: Optional[str] = Field(None, description="pH en KCl 1 M")
    ph_kcl_interpretacion: Optional[str] = Field(None, description="Interpretación del pH KCl")
    carbonato_calcio_equivalente: Optional[str] = Field(None, description="Carbonato de calcio equivalente (%)")
    carbonato_calcio_interpretacion: Optional[str] = Field(None, description="Interpretación del carbonato de calcio")
    conductividad_electrica: Optional[str] = Field(None, description="Conductividad eléctrica (dS m⁻¹)")
    conductividad_electrica_interpretacion: Optional[str] = Field(None, description="Interpretación de la conductividad eléctrica")
    
    # Resultados de fertilidad
    materia_organica: Optional[str] = Field(None, description="Materia orgánica (%)")
    materia_organica_interpretacion: Optional[str] = Field(None, description="Interpretación de materia orgánica")
    fosforo: Optional[str] = Field(None, description="Fósforo (mg kg⁻¹)")
    fosforo_interpretacion: Optional[str] = Field(None, description="Interpretación del fósforo")
    n_inorganico: Optional[str] = Field(None, description="Nitrógeno inorgánico (mg kg⁻¹)")
    n_inorganico_interpretacion: Optional[str] = Field(None, description="Interpretación del nitrógeno inorgánico")
    potasio: Optional[str] = Field(None, description="Potasio (mg kg⁻¹)")
    potasio_interpretacion: Optional[str] = Field(None, description="Interpretación del potasio")
    calcio: Optional[str] = Field(None, description="Calcio (mg kg⁻¹)")
    calcio_interpretacion: Optional[str] = Field(None, description="Interpretación del calcio")
    magnesio: Optional[str] = Field(None, description="Magnesio (mg kg⁻¹)")
    magnesio_interpretacion: Optional[str] = Field(None, description="Interpretación del magnesio")
    sodio: Optional[str] = Field(None, description="Sodio (mg kg⁻¹)")
    sodio_interpretacion: Optional[str] = Field(None, description="Interpretación del sodio")
    azufre: Optional[str] = Field(None, description="Azufre (mg kg⁻¹)")
    azufre_interpretacion: Optional[str] = Field(None, description="Interpretación del azufre")
    
    # Cationes intercambiables
    ca_porcentaje: Optional[str] = Field(None, description="Ca⁺² porcentaje")
    ca_me_100g: Optional[str] = Field(None, description="Ca⁺² me/100g")
    mg_porcentaje: Optional[str] = Field(None, description="Mg⁺² porcentaje")
    mg_me_100g: Optional[str] = Field(None, description="Mg⁺² me/100g")
    k_porcentaje: Optional[str] = Field(None, description="K⁺ porcentaje")
    k_me_100g: Optional[str] = Field(None, description="K⁺ me/100g")
    na_porcentaje: Optional[str] = Field(None, description="Na⁺ porcentaje")
    na_me_100g: Optional[str] = Field(None, description="Na⁺ me/100g")
    al_porcentaje: Optional[str] = Field(None, description="Al⁺³ porcentaje")
    al_me_100g: Optional[str] = Field(None, description="Al⁺³ me/100g")
    h_porcentaje: Optional[str] = Field(None, description="H⁺ porcentaje")
    h_me_100g: Optional[str] = Field(None, description="H⁺ me/100g")
    cic: Optional[str] = Field(None, description="Capacidad de Intercambio Catiónico")
    
    # Micronutrientes
    hierro: Optional[str] = Field(None, description="Hierro (mg kg⁻¹)")
    hierro_interpretacion: Optional[str] = Field(None, description="Interpretación del hierro")
    cobre: Optional[str] = Field(None, description="Cobre (mg kg⁻¹)")
    cobre_interpretacion: Optional[str] = Field(None, description="Interpretación del cobre")
    zinc: Optional[str] = Field(None, description="Zinc (mg kg⁻¹)")
    zinc_interpretacion: Optional[str] = Field(None, description="Interpretación del zinc")
    manganeso: Optional[str] = Field(None, description="Manganeso (mg kg⁻¹)")
    manganeso_interpretacion: Optional[str] = Field(None, description="Interpretación del manganeso")
    boro: Optional[str] = Field(None, description="Boro (mg kg⁻¹)")
    boro_interpretacion: Optional[str] = Field(None, description="Interpretación del boro")
    
    # Relaciones entre cationes
    ca_mg_relacion: Optional[str] = Field(None, description="Relación Ca/Mg")
    ca_mg_interpretacion: Optional[str] = Field(None, description="Interpretación de la relación Ca/Mg")
    mg_k_relacion: Optional[str] = Field(None, description="Relación Mg/K")
    mg_k_interpretacion: Optional[str] = Field(None, description="Interpretación de la relación Mg/K")
    ca_k_relacion: Optional[str] = Field(None, description="Relación Ca/K")
    ca_k_interpretacion: Optional[str] = Field(None, description="Interpretación de la relación Ca/K")
    ca_mg_k_relacion: Optional[str] = Field(None, description="Relación (Ca+Mg)/K")
    ca_mg_k_interpretacion: Optional[str] = Field(None, description="Interpretación de la relación (Ca+Mg)/K")
    k_mg_relacion: Optional[str] = Field(None, description="Relación K/Mg")
    k_mg_interpretacion: Optional[str] = Field(None, description="Interpretación de la relación K/Mg")

